namespace WinFormUI3Tier
{
    partial class frmPurchaseOrder
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            XS.WinForms.Controls.XpertGridViewDecimalColumn xpertGridViewDecimalColumn6 = new XS.WinForms.Controls.XpertGridViewDecimalColumn();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPurchaseOrder));
            XS.WinForms.Controls.XpertGridViewFinderColumn xpertGridViewFinderColumn2 = new XS.WinForms.Controls.XpertGridViewFinderColumn();
            XS.WinForms.Controls.XpertGridViewLabelColumn xpertGridViewLabelColumn3 = new XS.WinForms.Controls.XpertGridViewLabelColumn();
            XS.WinForms.Controls.XpertGridViewLabelColumn xpertGridViewLabelColumn4 = new XS.WinForms.Controls.XpertGridViewLabelColumn();
            XS.WinForms.Controls.XpertGridViewDecimalColumn xpertGridViewDecimalColumn7 = new XS.WinForms.Controls.XpertGridViewDecimalColumn();
            XS.WinForms.Controls.XpertGridViewDecimalColumn xpertGridViewDecimalColumn8 = new XS.WinForms.Controls.XpertGridViewDecimalColumn();
            XS.WinForms.Controls.XpertGridViewDecimalColumn xpertGridViewDecimalColumn9 = new XS.WinForms.Controls.XpertGridViewDecimalColumn();
            XS.WinForms.Controls.XpertGridViewDecimalColumn xpertGridViewDecimalColumn10 = new XS.WinForms.Controls.XpertGridViewDecimalColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition2 = new Telerik.WinControls.UI.TableViewDefinition();
            xpertSplitContainer1 = new XS.WinForms.Controls.XpertSplitContainer();
            gbxHeader = new XS.WinForms.Controls.XpertGroupBox();
            xpertGroupBox2 = new XS.WinForms.Controls.XpertGroupBox();
            pcbPhoto = new XS.WinForms.Controls.XpertPictureBox();
            txtVendor = new XS.WinForms.Controls.XpertFinder();
            lblVendor = new XS.WinForms.Controls.XpertLabel();
            lblDocumentAmount = new XS.WinForms.Controls.XpertLabel();
            txtDocAmt = new XS.WinForms.Controls.XpertNumberBox();
            dtpModifyDate = new XS.WinForms.Controls.XpertDateTime();
            lblModifyDate = new XS.WinForms.Controls.XpertLabel();
            lblCreateDateTime = new XS.WinForms.Controls.XpertLabel();
            dtpCreateDateTime = new XS.WinForms.Controls.XpertDateTime();
            txtRemarks = new XS.WinForms.Controls.XpertTextBox();
            lblRemarks = new XS.WinForms.Controls.XpertLabel();
            txtPOAmt = new XS.WinForms.Controls.XpertNumberBox();
            gbxDetails = new XS.WinForms.Controls.XpertGroupBox();
            gv1 = new XS.WinForms.Controls.XpertDataGridView();
            lblAmount = new XS.WinForms.Controls.XpertLabel();
            lblPODate = new XS.WinForms.Controls.XpertLabel();
            dtpPODate = new XS.WinForms.Controls.XpertDateTime();
            txtComments = new XS.WinForms.Controls.XpertTextBox();
            lblComments = new XS.WinForms.Controls.XpertLabel();
            lblPONo = new XS.WinForms.Controls.XpertLabel();
            txtPOCode = new XS.WinForms.Controls.XpertNavigator();
            xpertPageView1 = new XS.WinForms.Controls.XpertPageView();
            Page1 = new Telerik.WinControls.UI.RadPageViewPage();
            Page2 = new Telerik.WinControls.UI.RadPageViewPage();
            xpertGroupBox1 = new XS.WinForms.Controls.XpertGroupBox();
            xpertGroupBox3 = new XS.WinForms.Controls.XpertGroupBox();
            xpertRadioButton2 = new XS.WinForms.Controls.XpertRadioButton();
            xpertRadioButton1 = new XS.WinForms.Controls.XpertRadioButton();
            xpertLabel1 = new XS.WinForms.Controls.XpertLabel();
            txtItems = new XS.WinForms.Controls.XpertMultiSelctFinder();
            ((System.ComponentModel.ISupportInitialize)bindingSource1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)xpertSplitContainer1).BeginInit();
            xpertSplitContainer1.Panel1.SuspendLayout();
            xpertSplitContainer1.Panel2.SuspendLayout();
            xpertSplitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gbxHeader).BeginInit();
            gbxHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox2).BeginInit();
            xpertGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pcbPhoto).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblVendor).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblDocumentAmount).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txtDocAmt).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dtpModifyDate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblModifyDate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblCreateDateTime).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dtpCreateDateTime).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txtRemarks).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblRemarks).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txtPOAmt).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gbxDetails).BeginInit();
            gbxDetails.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gv1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gv1.MasterTemplate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblAmount).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblPODate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dtpPODate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txtComments).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblComments).BeginInit();
            ((System.ComponentModel.ISupportInitialize)lblPONo).BeginInit();
            ((System.ComponentModel.ISupportInitialize)xpertPageView1).BeginInit();
            xpertPageView1.SuspendLayout();
            Page1.SuspendLayout();
            Page2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox1).BeginInit();
            xpertGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox3).BeginInit();
            xpertGroupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)xpertRadioButton2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)xpertRadioButton1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)xpertLabel1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this).BeginInit();
            SuspendLayout();
            // 
            // xpertSplitContainer1
            // 
            xpertSplitContainer1.Control_Name = "xpertSplitContainer1";
            xpertSplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            xpertSplitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            xpertSplitContainer1.Location = new System.Drawing.Point(0, 0);
            xpertSplitContainer1.Name = "xpertSplitContainer1";
            xpertSplitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // xpertSplitContainer1.Panel1
            // 
            xpertSplitContainer1.Panel1.BackColor = System.Drawing.Color.FromArgb(191, 219, 255);
            xpertSplitContainer1.Panel1.Controls.Add(gbxHeader);
            // 
            // xpertSplitContainer1.Panel2
            // 
            xpertSplitContainer1.Panel2.Controls.Add(gbxDetails);
            xpertSplitContainer1.Size = new System.Drawing.Size(965, 344);
            xpertSplitContainer1.SplitterDistance = 166;
            xpertSplitContainer1.TabIndex = 2;
            xpertSplitContainer1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // gbxHeader
            // 
            gbxHeader.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            gbxHeader.BorderColor = System.Drawing.Color.Empty;
            gbxHeader.Control_Name = "gbxHeader";
            gbxHeader.Controls.Add(xpertGroupBox2);
            gbxHeader.Controls.Add(txtVendor);
            gbxHeader.Controls.Add(lblVendor);
            gbxHeader.Controls.Add(lblDocumentAmount);
            gbxHeader.Controls.Add(txtDocAmt);
            gbxHeader.Controls.Add(dtpModifyDate);
            gbxHeader.Controls.Add(lblModifyDate);
            gbxHeader.Controls.Add(lblCreateDateTime);
            gbxHeader.Controls.Add(dtpCreateDateTime);
            gbxHeader.Controls.Add(txtRemarks);
            gbxHeader.Controls.Add(lblRemarks);
            gbxHeader.Controls.Add(txtPOAmt);
            gbxHeader.Controls.Add(lblAmount);
            gbxHeader.Controls.Add(lblPODate);
            gbxHeader.Controls.Add(dtpPODate);
            gbxHeader.Controls.Add(txtComments);
            gbxHeader.Controls.Add(lblPONo);
            gbxHeader.Controls.Add(txtPOCode);
            gbxHeader.Controls.Add(lblComments);
            gbxHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            gbxHeader.GroupBoxStyle = Telerik.WinControls.UI.RadGroupBoxStyle.Office;
            gbxHeader.HeaderText = "Header";
            gbxHeader.Location = new System.Drawing.Point(0, 0);
            gbxHeader.Name = "gbxHeader";
            gbxHeader.Size = new System.Drawing.Size(965, 166);
            gbxHeader.TabIndex = 0;
            gbxHeader.Text = "Header";
            gbxHeader.Visibility_Criteria = null;
            gbxHeader.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertGroupBox2
            // 
            xpertGroupBox2.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            xpertGroupBox2.BorderColor = System.Drawing.Color.Empty;
            xpertGroupBox2.Control_Name = null;
            xpertGroupBox2.Controls.Add(pcbPhoto);
            xpertGroupBox2.GroupBoxStyle = Telerik.WinControls.UI.RadGroupBoxStyle.Office;
            xpertGroupBox2.HeaderText = "Photograph";
            xpertGroupBox2.Location = new System.Drawing.Point(778, 27);
            xpertGroupBox2.Name = "xpertGroupBox2";
            xpertGroupBox2.Size = new System.Drawing.Size(168, 124);
            xpertGroupBox2.TabIndex = 2;
            xpertGroupBox2.Text = "Photograph";
            xpertGroupBox2.Visibility_Criteria = null;
            xpertGroupBox2.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // pcbPhoto
            // 
            pcbPhoto.Calculation_Expression = null;
            pcbPhoto.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            pcbPhoto.Calculative = false;
            pcbPhoto.Column_Name = null;
            pcbPhoto.Control_Name = null;
            pcbPhoto.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            pcbPhoto.Custom_Data = false;
            pcbPhoto.Custom_Default = false;
            pcbPhoto.Display_Name = null;
            pcbPhoto.Dock = System.Windows.Forms.DockStyle.Fill;
            pcbPhoto.Field_Description = null;
            pcbPhoto.Field_Name = "filePhoto";
            pcbPhoto.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            pcbPhoto.Generated = false;
            pcbPhoto.Location = new System.Drawing.Point(2, 18);
            pcbPhoto.MaxSize = 1;
            pcbPhoto.MendatroryField = false;
            pcbPhoto.Metadata_Type = null;
            pcbPhoto.Name = "pcbPhoto";
            pcbPhoto.Size = new System.Drawing.Size(164, 104);
            pcbPhoto.TabIndex = 23;
            pcbPhoto.TabStop = false;
            pcbPhoto.Validation_Criteria = null;
            pcbPhoto.Visibility_Criteria = null;
            pcbPhoto.XpertDisplayMember = null;
            pcbPhoto.XpertValueMember = null;
            pcbPhoto.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtVendor
            // 
            txtVendor.Calculation_Expression = null;
            txtVendor.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtVendor.CalculationExpression = null;
            txtVendor.Calculative = false;
            txtVendor.Collection_Name = null;
            txtVendor.Column_Name = "POVCode";
            txtVendor.Control_Name = "txtVendor";
            txtVendor.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtVendor.Custom_Data = false;
            txtVendor.Custom_Datasource_Logic = false;
            txtVendor.Custom_Default = false;
            txtVendor.DataSource = null;
            txtVendor.Datasource_Assembly = "BlazorPWA.Client";
            txtVendor.Datasource_Namespace = "BlazorPWA.Client.Pages.MachineTest.Setup";
            txtVendor.Datasource_Program = "VendorMaster";
            txtVendor.Datasource_Type = XpertStudio.Common.Enums.XpertFinderConfigType.Pages;
            txtVendor.DescriptionLabel1 = null;
            txtVendor.DescriptionLabel2 = null;
            txtVendor.Display_Name = "Vendor";
            txtVendor.DisplayMember = null;
            txtVendor.DisplayMode = XpertStudio.Common.Enums.FinderDisplayOptions.Name;
            txtVendor.Enum_Name = null;
            txtVendor.Field_Description = null;
            txtVendor.Field_Name = "POVCode";
            txtVendor.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.Finder;
            txtVendor.FieldCode = null;
            txtVendor.FieldDesc = null;
            txtVendor.FieldMaxLength = 0;
            txtVendor.FieldName = null;
            txtVendor.Generated = false;
            txtVendor.Is_Grouping = false;
            txtVendor.isCalculatedField = false;
            txtVendor.IsSourceFromTable = false;
            txtVendor.IsSourceFromValueList = false;
            txtVendor.IsUnique = false;
            txtVendor.Key = false;
            txtVendor.Key_Column_Name = "VCode";
            txtVendor.Key_Property = null;
            txtVendor.Key_Value = null;
            txtVendor.Location = new System.Drawing.Point(125, 129);
            txtVendor.Mandatory = false;
            txtVendor.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            txtVendor.Max_Length = 0;
            txtVendor.Max_Size = 0;
            txtVendor.MendatroryField = false;
            txtVendor.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtVendor.Min_Length = 0;
            txtVendor.Min_Size = 0;
            txtVendor.Model_Name = null;
            txtVendor.MyFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            txtVendor.MyLinkLable1 = lblVendor;
            txtVendor.MyLinkLable2 = null;
            txtVendor.MyReadOnly = false;
            txtVendor.MyShowMasterFormButton = true;
            txtVendor.MyShowWriteUpButton = true;
            txtVendor.Name = "txtVendor";
            txtVendor.Name_Column_Name = "VName";
            txtVendor.Name_Property = null;
            txtVendor.Name_Value = null;
            txtVendor.Page_Key_Property = "ID";
            txtVendor.Page_Name_Property = "Description";
            txtVendor.Query_Class_Name = null;
            txtVendor.ReferenceFieldDesc = null;
            txtVendor.ReferenceFieldName = null;
            txtVendor.ReferenceTableName = null;
            txtVendor.Required = false;
            txtVendor.ShowDataSource = false;
            txtVendor.Size = new System.Drawing.Size(227, 22);
            txtVendor.SQLMethodName = null;
            txtVendor.TabIndex = 18;
            txtVendor.Table_Name = "TSPL_VENDOR_MASTER";
            txtVendor.Tag_Column_Name = null;
            txtVendor.Tag_Property = null;
            txtVendor.Validation_Criteria = null;
            txtVendor.Value = "";
            txtVendor.ValueMember = null;
            txtVendor.Visibility_Criteria = null;
            txtVendor.Web_Page_Name = "VendorMaster";
            txtVendor.Web_Page_Url = "/MachineTest/Setup/VendorMaster";
            txtVendor.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblVendor
            // 
            lblVendor.Calculation_Expression = null;
            lblVendor.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblVendor.Calculative = false;
            lblVendor.Column_Name = null;
            lblVendor.Control_Name = "lblVendor";
            lblVendor.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblVendor.Custom_Data = false;
            lblVendor.Custom_Default = false;
            lblVendor.Display_Name = null;
            lblVendor.Field_Description = null;
            lblVendor.Field_Name = null;
            lblVendor.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblVendor.FieldName = null;
            lblVendor.Generated = false;
            lblVendor.Location = new System.Drawing.Point(33, 133);
            lblVendor.MendatroryField = false;
            lblVendor.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblVendor.Name = "lblVendor";
            lblVendor.Size = new System.Drawing.Size(43, 18);
            lblVendor.SourceColumn = null;
            lblVendor.TabIndex = 19;
            lblVendor.Text = "Vendor";
            lblVendor.Validation_Criteria = null;
            lblVendor.Visibility_Criteria = null;
            lblVendor.XpertDisplayMember = null;
            lblVendor.XpertValueMember = null;
            lblVendor.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblDocumentAmount
            // 
            lblDocumentAmount.Calculation_Expression = null;
            lblDocumentAmount.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblDocumentAmount.Calculative = false;
            lblDocumentAmount.Column_Name = null;
            lblDocumentAmount.Control_Name = null;
            lblDocumentAmount.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblDocumentAmount.Custom_Data = false;
            lblDocumentAmount.Custom_Default = false;
            lblDocumentAmount.Display_Name = null;
            lblDocumentAmount.Field_Description = null;
            lblDocumentAmount.Field_Name = null;
            lblDocumentAmount.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblDocumentAmount.FieldName = null;
            lblDocumentAmount.Generated = false;
            lblDocumentAmount.Location = new System.Drawing.Point(500, 133);
            lblDocumentAmount.MendatroryField = false;
            lblDocumentAmount.Metadata_Type = null;
            lblDocumentAmount.Name = "lblDocumentAmount";
            lblDocumentAmount.Size = new System.Drawing.Size(102, 18);
            lblDocumentAmount.SourceColumn = null;
            lblDocumentAmount.TabIndex = 21;
            lblDocumentAmount.Text = "Document Amount";
            lblDocumentAmount.Validation_Criteria = null;
            lblDocumentAmount.Visibility_Criteria = null;
            lblDocumentAmount.XpertDisplayMember = null;
            lblDocumentAmount.XpertValueMember = null;
            lblDocumentAmount.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtDocAmt
            // 
            txtDocAmt.Aggregate_Field = null;
            txtDocAmt.Aggregate_Type = null;
            txtDocAmt.Calculation_Expression = null;
            txtDocAmt.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtDocAmt.CalculationExpression = null;
            txtDocAmt.Calculative = false;
            txtDocAmt.Column_Name = "Document_Amount";
            txtDocAmt.Control_Name = null;
            txtDocAmt.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModel;
            txtDocAmt.Custom_Data = false;
            txtDocAmt.Custom_Default = false;
            txtDocAmt.DecimalPlaces = 0;
            txtDocAmt.Display_Name = "Document Amount";
            txtDocAmt.ExpressionContainer = null;
            txtDocAmt.ExpressionGrid = null;
            txtDocAmt.Field_Description = null;
            txtDocAmt.Field_Name = "Document_Amount";
            txtDocAmt.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            txtDocAmt.FieldCode = null;
            txtDocAmt.FieldDesc = null;
            txtDocAmt.FieldMaxLength = 0;
            txtDocAmt.FieldName = "Document_Amount";
            txtDocAmt.Generated = false;
            txtDocAmt.isCalculatedField = false;
            txtDocAmt.IsSourceFromTable = false;
            txtDocAmt.IsSourceFromValueList = false;
            txtDocAmt.IsUnique = false;
            txtDocAmt.Key = false;
            txtDocAmt.Location = new System.Drawing.Point(610, 131);
            txtDocAmt.MandatoryField = false;
            txtDocAmt.Max_Length = 0;
            txtDocAmt.MendatroryField = false;
            txtDocAmt.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtDocAmt.Min_Length = 0;
            txtDocAmt.MyLinkLable1 = lblDocumentAmount;
            txtDocAmt.MyLinkLable2 = null;
            txtDocAmt.Name = "txtDocAmt";
            txtDocAmt.Number_Type = XpertStudio.Common.Enums.XpertNumberTypes.Decimal;
            txtDocAmt.ReferenceFieldDesc = null;
            txtDocAmt.ReferenceFieldName = "Document_Amount";
            txtDocAmt.ReferenceTableName = null;
            txtDocAmt.Size = new System.Drawing.Size(150, 20);
            txtDocAmt.TabIndex = 20;
            txtDocAmt.Text = "0";
            txtDocAmt.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            txtDocAmt.Validation_Criteria = "Model.POTotAmt==Model.Document_Amount";
            txtDocAmt.Value = 0D;
            txtDocAmt.Visibility_Criteria = "";
            txtDocAmt.XpertDisplayMember = null;
            txtDocAmt.XpertValueMember = null;
            txtDocAmt.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // dtpModifyDate
            // 
            dtpModifyDate.Calculation_Expression = null;
            dtpModifyDate.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            dtpModifyDate.CalculationExpression = null;
            dtpModifyDate.Calculative = false;
            dtpModifyDate.Column_Name = "ModifiyDate";
            dtpModifyDate.Control_Name = "dtpModifyDate";
            dtpModifyDate.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            dtpModifyDate.Custom_Data = false;
            dtpModifyDate.Custom_Default = false;
            dtpModifyDate.CustomFormat = "dd/MM/yyyy hh:mm tt";
            dtpModifyDate.Display_Name = "Modify Date";
            dtpModifyDate.Field_Description = null;
            dtpModifyDate.Field_Name = "ModifiyDate";
            dtpModifyDate.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            dtpModifyDate.FieldCode = null;
            dtpModifyDate.FieldDesc = null;
            dtpModifyDate.FieldMaxLength = 0;
            dtpModifyDate.FieldName = "ModifiyDate";
            dtpModifyDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtpModifyDate.Generated = false;
            dtpModifyDate.isCalculatedField = false;
            dtpModifyDate.IsSourceFromTable = false;
            dtpModifyDate.IsSourceFromValueList = false;
            dtpModifyDate.IsUnique = false;
            dtpModifyDate.Key = false;
            dtpModifyDate.Location = new System.Drawing.Point(610, 106);
            dtpModifyDate.Max_Length = 0;
            dtpModifyDate.MendatroryField = false;
            dtpModifyDate.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            dtpModifyDate.Min_Length = 0;
            dtpModifyDate.MyLinkLable1 = lblModifyDate;
            dtpModifyDate.MyLinkLable2 = null;
            dtpModifyDate.Name = "dtpModifyDate";
            dtpModifyDate.ReferenceFieldDesc = null;
            dtpModifyDate.ReferenceFieldName = "ModifiyDate";
            dtpModifyDate.ReferenceTableName = null;
            dtpModifyDate.Size = new System.Drawing.Size(150, 20);
            dtpModifyDate.TabIndex = 17;
            dtpModifyDate.TabStop = false;
            dtpModifyDate.Text = "22-05-2024 11:18 PM";
            dtpModifyDate.Validation_Criteria = null;
            dtpModifyDate.Value = new System.DateTime(2024, 5, 22, 23, 18, 13, 551);
            dtpModifyDate.Visibility_Criteria = null;
            dtpModifyDate.XpertDisplayMember = null;
            dtpModifyDate.XpertValueMember = null;
            dtpModifyDate.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.Design;
            // 
            // lblModifyDate
            // 
            lblModifyDate.Calculation_Expression = null;
            lblModifyDate.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblModifyDate.Calculative = false;
            lblModifyDate.Column_Name = null;
            lblModifyDate.Control_Name = "lblModifyDate";
            lblModifyDate.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblModifyDate.Custom_Data = false;
            lblModifyDate.Custom_Default = false;
            lblModifyDate.Display_Name = null;
            lblModifyDate.Field_Description = null;
            lblModifyDate.Field_Name = null;
            lblModifyDate.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblModifyDate.FieldName = null;
            lblModifyDate.Generated = false;
            lblModifyDate.Location = new System.Drawing.Point(514, 106);
            lblModifyDate.MendatroryField = false;
            lblModifyDate.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblModifyDate.Name = "lblModifyDate";
            lblModifyDate.Size = new System.Drawing.Size(68, 18);
            lblModifyDate.SourceColumn = null;
            lblModifyDate.TabIndex = 16;
            lblModifyDate.Text = "Modify Date";
            lblModifyDate.Validation_Criteria = null;
            lblModifyDate.Visibility_Criteria = null;
            lblModifyDate.XpertDisplayMember = null;
            lblModifyDate.XpertValueMember = null;
            lblModifyDate.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblCreateDateTime
            // 
            lblCreateDateTime.Calculation_Expression = null;
            lblCreateDateTime.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblCreateDateTime.Calculative = false;
            lblCreateDateTime.Column_Name = null;
            lblCreateDateTime.Control_Name = "lblCreateDateTime";
            lblCreateDateTime.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblCreateDateTime.Custom_Data = false;
            lblCreateDateTime.Custom_Default = false;
            lblCreateDateTime.Display_Name = null;
            lblCreateDateTime.Field_Description = null;
            lblCreateDateTime.Field_Name = null;
            lblCreateDateTime.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblCreateDateTime.FieldName = null;
            lblCreateDateTime.Generated = false;
            lblCreateDateTime.Location = new System.Drawing.Point(512, 82);
            lblCreateDateTime.MendatroryField = false;
            lblCreateDateTime.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblCreateDateTime.Name = "lblCreateDateTime";
            lblCreateDateTime.Size = new System.Drawing.Size(90, 18);
            lblCreateDateTime.SourceColumn = null;
            lblCreateDateTime.TabIndex = 15;
            lblCreateDateTime.Text = "Create DateTime";
            lblCreateDateTime.Validation_Criteria = null;
            lblCreateDateTime.Visibility_Criteria = null;
            lblCreateDateTime.XpertDisplayMember = null;
            lblCreateDateTime.XpertValueMember = null;
            lblCreateDateTime.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // dtpCreateDateTime
            // 
            dtpCreateDateTime.Calculation_Expression = null;
            dtpCreateDateTime.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            dtpCreateDateTime.CalculationExpression = null;
            dtpCreateDateTime.Calculative = false;
            dtpCreateDateTime.Column_Name = "CreateDate";
            dtpCreateDateTime.Control_Name = "dtpCreateDateTime";
            dtpCreateDateTime.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            dtpCreateDateTime.Custom_Data = false;
            dtpCreateDateTime.Custom_Default = false;
            dtpCreateDateTime.CustomFormat = "dd/MM/yyyy hh:mm tt";
            dtpCreateDateTime.Display_Name = "Create DateTime";
            dtpCreateDateTime.Field_Description = null;
            dtpCreateDateTime.Field_Name = "CreateDate";
            dtpCreateDateTime.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            dtpCreateDateTime.FieldCode = null;
            dtpCreateDateTime.FieldDesc = null;
            dtpCreateDateTime.FieldMaxLength = 0;
            dtpCreateDateTime.FieldName = "CreateDate";
            dtpCreateDateTime.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtpCreateDateTime.Generated = false;
            dtpCreateDateTime.isCalculatedField = false;
            dtpCreateDateTime.IsSourceFromTable = false;
            dtpCreateDateTime.IsSourceFromValueList = false;
            dtpCreateDateTime.IsUnique = false;
            dtpCreateDateTime.Key = false;
            dtpCreateDateTime.Location = new System.Drawing.Point(610, 80);
            dtpCreateDateTime.Max_Length = 0;
            dtpCreateDateTime.MendatroryField = false;
            dtpCreateDateTime.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            dtpCreateDateTime.Min_Length = 0;
            dtpCreateDateTime.MyLinkLable1 = lblCreateDateTime;
            dtpCreateDateTime.MyLinkLable2 = null;
            dtpCreateDateTime.Name = "dtpCreateDateTime";
            dtpCreateDateTime.ReferenceFieldDesc = null;
            dtpCreateDateTime.ReferenceFieldName = "CreateDate";
            dtpCreateDateTime.ReferenceTableName = null;
            dtpCreateDateTime.Size = new System.Drawing.Size(150, 20);
            dtpCreateDateTime.TabIndex = 14;
            dtpCreateDateTime.TabStop = false;
            dtpCreateDateTime.Text = "22-05-2024 10:25 PM";
            dtpCreateDateTime.Validation_Criteria = null;
            dtpCreateDateTime.Value = new System.DateTime(2024, 5, 22, 22, 25, 31, 234);
            dtpCreateDateTime.Visibility_Criteria = null;
            dtpCreateDateTime.XpertDisplayMember = null;
            dtpCreateDateTime.XpertValueMember = null;
            dtpCreateDateTime.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.Design;
            // 
            // txtRemarks
            // 
            txtRemarks.Calculation_Expression = null;
            txtRemarks.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtRemarks.CalculationExpression = null;
            txtRemarks.Calculative = false;
            txtRemarks.Column_Name = "PORemarks";
            txtRemarks.Control_Name = "txtRemarks";
            txtRemarks.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtRemarks.Custom_Data = false;
            txtRemarks.Custom_Default = false;
            txtRemarks.Display_Name = "Remarks";
            txtRemarks.Field_Description = null;
            txtRemarks.Field_Name = "PORemarks";
            txtRemarks.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            txtRemarks.FieldCode = null;
            txtRemarks.FieldDesc = null;
            txtRemarks.FieldMaxLength = 50;
            txtRemarks.FieldName = "PORemarks";
            txtRemarks.Generated = false;
            txtRemarks.isCalculatedField = false;
            txtRemarks.IsSourceFromTable = false;
            txtRemarks.IsSourceFromValueList = false;
            txtRemarks.IsUnique = false;
            txtRemarks.Key = false;
            txtRemarks.Location = new System.Drawing.Point(125, 80);
            txtRemarks.Max_Length = 50;
            txtRemarks.MendatroryField = false;
            txtRemarks.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtRemarks.Min_Length = 0;
            txtRemarks.MyLinkLable1 = lblRemarks;
            txtRemarks.MyLinkLable2 = null;
            txtRemarks.Name = "txtRemarks";
            txtRemarks.ReferenceFieldDesc = null;
            txtRemarks.ReferenceFieldName = "PORemarks";
            txtRemarks.ReferenceTableName = null;
            txtRemarks.Size = new System.Drawing.Size(378, 20);
            txtRemarks.TabIndex = 13;
            txtRemarks.Validation_Criteria = null;
            txtRemarks.Visibility_Criteria = null;
            txtRemarks.XpertDisplayMember = null;
            txtRemarks.XpertValueMember = null;
            txtRemarks.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblRemarks
            // 
            lblRemarks.Calculation_Expression = null;
            lblRemarks.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblRemarks.Calculative = false;
            lblRemarks.Column_Name = null;
            lblRemarks.Control_Name = "lblDescription";
            lblRemarks.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblRemarks.Custom_Data = false;
            lblRemarks.Custom_Default = false;
            lblRemarks.Display_Name = null;
            lblRemarks.Field_Description = null;
            lblRemarks.Field_Name = null;
            lblRemarks.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblRemarks.FieldName = null;
            lblRemarks.Generated = false;
            lblRemarks.Location = new System.Drawing.Point(33, 82);
            lblRemarks.MendatroryField = false;
            lblRemarks.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblRemarks.Name = "lblRemarks";
            lblRemarks.Size = new System.Drawing.Size(49, 18);
            lblRemarks.SourceColumn = null;
            lblRemarks.TabIndex = 12;
            lblRemarks.Text = "Remarks";
            lblRemarks.Validation_Criteria = null;
            lblRemarks.Visibility_Criteria = null;
            lblRemarks.XpertDisplayMember = null;
            lblRemarks.XpertValueMember = null;
            lblRemarks.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtPOAmt
            // 
            txtPOAmt.Aggregate_Field = "POIAmt";
            txtPOAmt.Aggregate_Type = XpertStudio.Common.Enums.XSAggregateType.Sum;
            txtPOAmt.Calculation_Expression = null;
            txtPOAmt.Calculation_Type = XS.WinForms.Controls.CalculationTypes.UI;
            txtPOAmt.CalculationExpression = null;
            txtPOAmt.Calculative = true;
            txtPOAmt.Column_Name = "POTotAmt";
            txtPOAmt.Control_Name = "txtPOAmt";
            txtPOAmt.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtPOAmt.Custom_Data = false;
            txtPOAmt.Custom_Default = false;
            txtPOAmt.DecimalPlaces = 2;
            txtPOAmt.Display_Name = "Amount";
            txtPOAmt.ExpressionContainer = gbxDetails;
            txtPOAmt.ExpressionGrid = gv1;
            txtPOAmt.Field_Description = null;
            txtPOAmt.Field_Name = "POTotAmt";
            txtPOAmt.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            txtPOAmt.FieldCode = null;
            txtPOAmt.FieldDesc = null;
            txtPOAmt.FieldMaxLength = 0;
            txtPOAmt.FieldName = "POTotAmt";
            txtPOAmt.Generated = false;
            txtPOAmt.isCalculatedField = true;
            txtPOAmt.IsSourceFromTable = false;
            txtPOAmt.IsSourceFromValueList = false;
            txtPOAmt.IsUnique = false;
            txtPOAmt.Key = false;
            txtPOAmt.Location = new System.Drawing.Point(125, 103);
            txtPOAmt.MandatoryField = false;
            txtPOAmt.Max_Length = 0;
            txtPOAmt.MendatroryField = false;
            txtPOAmt.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtPOAmt.Min_Length = 0;
            txtPOAmt.MyLinkLable1 = lblAmount;
            txtPOAmt.MyLinkLable2 = null;
            txtPOAmt.Name = "txtPOAmt";
            txtPOAmt.Number_Type = XpertStudio.Common.Enums.XpertNumberTypes.Decimal;
            txtPOAmt.ReadOnly = true;
            txtPOAmt.ReferenceFieldDesc = null;
            txtPOAmt.ReferenceFieldName = "POTotAmt";
            txtPOAmt.ReferenceTableName = null;
            txtPOAmt.Size = new System.Drawing.Size(247, 20);
            txtPOAmt.TabIndex = 11;
            txtPOAmt.Text = "0";
            txtPOAmt.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            txtPOAmt.Validation_Criteria = null;
            txtPOAmt.Value = 0D;
            txtPOAmt.Visibility_Criteria = null;
            txtPOAmt.XpertDisplayMember = null;
            txtPOAmt.XpertValueMember = null;
            txtPOAmt.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // gbxDetails
            // 
            gbxDetails.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            gbxDetails.BackColor = System.Drawing.Color.FromArgb(191, 219, 255);
            gbxDetails.BorderColor = System.Drawing.Color.Empty;
            gbxDetails.Control_Name = "gbxDetails";
            gbxDetails.Controls.Add(gv1);
            gbxDetails.Dock = System.Windows.Forms.DockStyle.Fill;
            gbxDetails.GroupBoxStyle = Telerik.WinControls.UI.RadGroupBoxStyle.Office;
            gbxDetails.HeaderText = "Details";
            gbxDetails.Location = new System.Drawing.Point(0, 0);
            gbxDetails.Name = "gbxDetails";
            gbxDetails.Size = new System.Drawing.Size(965, 174);
            gbxDetails.TabIndex = 1;
            gbxDetails.Text = "Details";
            gbxDetails.Visibility_Criteria = "Model.Document_Amount>0";
            gbxDetails.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // gv1
            // 
            gv1.Calculation_Expression = null;
            gv1.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            gv1.Calculative = false;
            gv1.Class_Name = "clsPO_Item";
            gv1.Column_Mode = XpertStudio.Common.Enums.XSGridColumnMode.Design;
            gv1.Column_Name = "POCode";
            gv1.Control_Name = "gv1";
            gv1.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            gv1.Custom_Data = false;
            gv1.Custom_Default = false;
            gv1.Display_Name = "Details";
            gv1.Dock = System.Windows.Forms.DockStyle.Fill;
            gv1.Field_Description = null;
            gv1.Field_Name = "PO_Items";
            gv1.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            gv1.Generated = false;
            gv1.GridType = XpertStudio.Common.Enums.XSGridType.Grid;
            gv1.Location = new System.Drawing.Point(2, 18);
            // 
            // 
            // 
            xpertGridViewDecimalColumn6.Aggregate_Type = null;
            xpertGridViewDecimalColumn6.Calculation_Expression = null;
            xpertGridViewDecimalColumn6.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewDecimalColumn6.Calculative = false;
            xpertGridViewDecimalColumn6.Column_Name = "POISNo";
            xpertGridViewDecimalColumn6.Control_Name = "POISNo";
            xpertGridViewDecimalColumn6.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewDecimalColumn6.Custom_Data = false;
            xpertGridViewDecimalColumn6.Custom_Default = false;
            xpertGridViewDecimalColumn6.DecimalPlaces = 0;
            xpertGridViewDecimalColumn6.Display_Name = null;
            xpertGridViewDecimalColumn6.Field_Description = "Row No";
            xpertGridViewDecimalColumn6.Field_Name = "POISNo";
            xpertGridViewDecimalColumn6.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.RowNo;
            xpertGridViewDecimalColumn6.FieldName = "POISNo";
            xpertGridViewDecimalColumn6.Generated = false;
            xpertGridViewDecimalColumn6.HeaderText = "Row No";
            xpertGridViewDecimalColumn6.Maximum = new decimal(new int[] { 10000, 0, 0, 0 });
            xpertGridViewDecimalColumn6.MendatroryField = false;
            xpertGridViewDecimalColumn6.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewDecimalColumn6.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            xpertGridViewDecimalColumn6.Name = "POISNo";
            xpertGridViewDecimalColumn6.Nullable = false;
            xpertGridViewDecimalColumn6.Validation_Criteria = null;
            xpertGridViewDecimalColumn6.Visibility_Criteria = null;
            xpertGridViewDecimalColumn6.Width = 80;
            xpertGridViewDecimalColumn6.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewDecimalColumn6.XpertBindingSource");
            xpertGridViewDecimalColumn6.XpertDisplayMember = null;
            xpertGridViewDecimalColumn6.XpertValueMember = null;
            xpertGridViewDecimalColumn6.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewFinderColumn2.Calculation_Expression = null;
            xpertGridViewFinderColumn2.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewFinderColumn2.Calculative = false;
            xpertGridViewFinderColumn2.Collection_Name = null;
            xpertGridViewFinderColumn2.Column_Name = "POICode";
            xpertGridViewFinderColumn2.Control_Name = "POICode";
            xpertGridViewFinderColumn2.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewFinderColumn2.Custom_Data = false;
            xpertGridViewFinderColumn2.Custom_Datasource_Logic = false;
            xpertGridViewFinderColumn2.Custom_Default = false;
            xpertGridViewFinderColumn2.Datasource_Assembly = "BlazorPWA.Client";
            xpertGridViewFinderColumn2.Datasource_Namespace = "BlazorPWA.Client.Pages.MachineTest.Setup";
            xpertGridViewFinderColumn2.Datasource_Program = "ItemMaster";
            xpertGridViewFinderColumn2.Datasource_Type = XpertStudio.Common.Enums.XpertFinderConfigType.Pages;
            xpertGridViewFinderColumn2.Display_Name = null;
            xpertGridViewFinderColumn2.Enum_Name = null;
            xpertGridViewFinderColumn2.Field_Description = null;
            xpertGridViewFinderColumn2.Field_Name = "POICode";
            xpertGridViewFinderColumn2.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewFinderColumn2.FieldName = "POICode";
            xpertGridViewFinderColumn2.Generated = false;
            xpertGridViewFinderColumn2.HeaderText = "Item Code";
            xpertGridViewFinderColumn2.Key_Column_Name = "ICode";
            xpertGridViewFinderColumn2.Key_Property = null;
            xpertGridViewFinderColumn2.Key_Value = null;
            xpertGridViewFinderColumn2.MendatroryField = false;
            xpertGridViewFinderColumn2.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewFinderColumn2.MinWidth = 1;
            xpertGridViewFinderColumn2.Model_Name = "";
            xpertGridViewFinderColumn2.Name = "POICode";
            xpertGridViewFinderColumn2.Name_Column_Name = "IName";
            xpertGridViewFinderColumn2.Name_Property = "Description";
            xpertGridViewFinderColumn2.Name_Value = null;
            xpertGridViewFinderColumn2.Nullable = false;
            xpertGridViewFinderColumn2.Page_Key_Property = "ID";
            xpertGridViewFinderColumn2.Page_Name_Property = "Description";
            xpertGridViewFinderColumn2.Query_Class_Name = null;
            xpertGridViewFinderColumn2.SQLMethodName = null;
            xpertGridViewFinderColumn2.Table_Name = "TSPL_ITEM_MASTER";
            xpertGridViewFinderColumn2.Tag_Column_Name = null;
            xpertGridViewFinderColumn2.Tag_Property = null;
            xpertGridViewFinderColumn2.Validation_Criteria = null;
            xpertGridViewFinderColumn2.Visibility_Criteria = null;
            xpertGridViewFinderColumn2.Web_Page_Name = "ItemMaster";
            xpertGridViewFinderColumn2.Web_Page_Url = "/MachineTest/Setup/ItemMasters";
            xpertGridViewFinderColumn2.Width = 300;
            xpertGridViewFinderColumn2.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewLabelColumn3.Calculation_Expression = null;
            xpertGridViewLabelColumn3.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewLabelColumn3.Calculative = false;
            xpertGridViewLabelColumn3.Column_Name = "";
            xpertGridViewLabelColumn3.Control_Name = "ItemName";
            xpertGridViewLabelColumn3.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModel;
            xpertGridViewLabelColumn3.Custom_Data = false;
            xpertGridViewLabelColumn3.Custom_Default = false;
            xpertGridViewLabelColumn3.Display_Name = null;
            xpertGridViewLabelColumn3.Field_Description = "Item Name";
            xpertGridViewLabelColumn3.Field_Name = "ItemName";
            xpertGridViewLabelColumn3.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewLabelColumn3.FieldName = "ItemName";
            xpertGridViewLabelColumn3.Generated = false;
            xpertGridViewLabelColumn3.HeaderText = "Item Name";
            xpertGridViewLabelColumn3.MendatroryField = false;
            xpertGridViewLabelColumn3.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewLabelColumn3.Name = "ItemName";
            xpertGridViewLabelColumn3.Nullable = false;
            xpertGridViewLabelColumn3.SourceColumn = "POICode";
            xpertGridViewLabelColumn3.Url = null;
            xpertGridViewLabelColumn3.Validation_Criteria = null;
            xpertGridViewLabelColumn3.Visibility_Criteria = null;
            xpertGridViewLabelColumn3.Width = 150;
            xpertGridViewLabelColumn3.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewLabelColumn3.XpertBindingSource");
            xpertGridViewLabelColumn3.XpertDisplayMember = null;
            xpertGridViewLabelColumn3.XpertValueMember = null;
            xpertGridViewLabelColumn3.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewLabelColumn4.Calculation_Expression = null;
            xpertGridViewLabelColumn4.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewLabelColumn4.Calculative = false;
            xpertGridViewLabelColumn4.Column_Name = "POIUOM";
            xpertGridViewLabelColumn4.Control_Name = "Uom";
            xpertGridViewLabelColumn4.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewLabelColumn4.Custom_Data = false;
            xpertGridViewLabelColumn4.Custom_Default = false;
            xpertGridViewLabelColumn4.Display_Name = null;
            xpertGridViewLabelColumn4.Field_Description = "UOM";
            xpertGridViewLabelColumn4.Field_Name = "POIUOM";
            xpertGridViewLabelColumn4.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewLabelColumn4.FieldName = "POIUOM";
            xpertGridViewLabelColumn4.Generated = false;
            xpertGridViewLabelColumn4.HeaderText = "UOM";
            xpertGridViewLabelColumn4.MendatroryField = false;
            xpertGridViewLabelColumn4.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewLabelColumn4.MinWidth = 1;
            xpertGridViewLabelColumn4.Name = "Uom";
            xpertGridViewLabelColumn4.Nullable = false;
            xpertGridViewLabelColumn4.SourceColumn = "POICode";
            xpertGridViewLabelColumn4.Url = null;
            xpertGridViewLabelColumn4.Validation_Criteria = null;
            xpertGridViewLabelColumn4.Visibility_Criteria = null;
            xpertGridViewLabelColumn4.Width = 100;
            xpertGridViewLabelColumn4.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewLabelColumn4.XpertBindingSource");
            xpertGridViewLabelColumn4.XpertDisplayMember = null;
            xpertGridViewLabelColumn4.XpertValueMember = null;
            xpertGridViewLabelColumn4.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewDecimalColumn7.Aggregate_Type = null;
            xpertGridViewDecimalColumn7.Calculation_Expression = null;
            xpertGridViewDecimalColumn7.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewDecimalColumn7.Calculative = false;
            xpertGridViewDecimalColumn7.Column_Name = "";
            xpertGridViewDecimalColumn7.Control_Name = "POIRate";
            xpertGridViewDecimalColumn7.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewDecimalColumn7.Custom_Data = false;
            xpertGridViewDecimalColumn7.Custom_Default = false;
            xpertGridViewDecimalColumn7.Display_Name = null;
            xpertGridViewDecimalColumn7.Field_Description = "POIRate";
            xpertGridViewDecimalColumn7.Field_Name = "POIRate";
            xpertGridViewDecimalColumn7.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewDecimalColumn7.FieldName = "POIRate";
            xpertGridViewDecimalColumn7.Generated = false;
            xpertGridViewDecimalColumn7.HeaderText = "Rate";
            xpertGridViewDecimalColumn7.Maximum = new decimal(new int[] { 10000000, 0, 0, 0 });
            xpertGridViewDecimalColumn7.MendatroryField = false;
            xpertGridViewDecimalColumn7.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewDecimalColumn7.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            xpertGridViewDecimalColumn7.Name = "POIRate";
            xpertGridViewDecimalColumn7.Validation_Criteria = null;
            xpertGridViewDecimalColumn7.Visibility_Criteria = null;
            xpertGridViewDecimalColumn7.Width = 100;
            xpertGridViewDecimalColumn7.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewDecimalColumn7.XpertBindingSource");
            xpertGridViewDecimalColumn7.XpertDisplayMember = null;
            xpertGridViewDecimalColumn7.XpertValueMember = null;
            xpertGridViewDecimalColumn7.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewDecimalColumn8.Aggregate_Type = XpertStudio.Common.Enums.XSAggregateType.Sum;
            xpertGridViewDecimalColumn8.Calculation_Expression = null;
            xpertGridViewDecimalColumn8.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewDecimalColumn8.Calculative = false;
            xpertGridViewDecimalColumn8.Column_Name = "";
            xpertGridViewDecimalColumn8.Control_Name = "POIQty";
            xpertGridViewDecimalColumn8.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewDecimalColumn8.Custom_Data = false;
            xpertGridViewDecimalColumn8.Custom_Default = false;
            xpertGridViewDecimalColumn8.Display_Name = null;
            xpertGridViewDecimalColumn8.Field_Description = null;
            xpertGridViewDecimalColumn8.Field_Name = "POIQty";
            xpertGridViewDecimalColumn8.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewDecimalColumn8.FieldName = "POIQty";
            xpertGridViewDecimalColumn8.Generated = false;
            xpertGridViewDecimalColumn8.HeaderText = "Quantity";
            xpertGridViewDecimalColumn8.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
            xpertGridViewDecimalColumn8.MendatroryField = false;
            xpertGridViewDecimalColumn8.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewDecimalColumn8.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            xpertGridViewDecimalColumn8.Name = "POIQty";
            xpertGridViewDecimalColumn8.Validation_Criteria = null;
            xpertGridViewDecimalColumn8.Visibility_Criteria = null;
            xpertGridViewDecimalColumn8.Width = 100;
            xpertGridViewDecimalColumn8.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewDecimalColumn8.XpertBindingSource");
            xpertGridViewDecimalColumn8.XpertDisplayMember = null;
            xpertGridViewDecimalColumn8.XpertValueMember = null;
            xpertGridViewDecimalColumn8.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewDecimalColumn9.Aggregate_Type = XpertStudio.Common.Enums.XSAggregateType.Sum;
            xpertGridViewDecimalColumn9.Calculation_Expression = "POIRate*POIQty";
            xpertGridViewDecimalColumn9.Calculation_Type = XS.WinForms.Controls.CalculationTypes.UI;
            xpertGridViewDecimalColumn9.Calculative = true;
            xpertGridViewDecimalColumn9.Column_Name = "";
            xpertGridViewDecimalColumn9.Control_Name = "POIAmt";
            xpertGridViewDecimalColumn9.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertGridViewDecimalColumn9.Custom_Data = false;
            xpertGridViewDecimalColumn9.Custom_Default = false;
            xpertGridViewDecimalColumn9.Display_Name = null;
            xpertGridViewDecimalColumn9.EnableExpressionEditor = true;
            xpertGridViewDecimalColumn9.Expression = "Math.Round((_POIRate ?? 0) * (_POIQty ?? 0), 2)";
            xpertGridViewDecimalColumn9.Field_Description = "Amount";
            xpertGridViewDecimalColumn9.Field_Name = "POIAmt";
            xpertGridViewDecimalColumn9.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewDecimalColumn9.FieldName = "POIAmt";
            xpertGridViewDecimalColumn9.Generated = false;
            xpertGridViewDecimalColumn9.HeaderText = "Amount";
            xpertGridViewDecimalColumn9.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
            xpertGridViewDecimalColumn9.MendatroryField = false;
            xpertGridViewDecimalColumn9.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewDecimalColumn9.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
            xpertGridViewDecimalColumn9.Name = "POIAmt";
            xpertGridViewDecimalColumn9.Validation_Criteria = null;
            xpertGridViewDecimalColumn9.Visibility_Criteria = null;
            xpertGridViewDecimalColumn9.Width = 100;
            xpertGridViewDecimalColumn9.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewDecimalColumn9.XpertBindingSource");
            xpertGridViewDecimalColumn9.XpertDisplayMember = null;
            xpertGridViewDecimalColumn9.XpertValueMember = null;
            xpertGridViewDecimalColumn9.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            xpertGridViewDecimalColumn10.Aggregate_Type = null;
            xpertGridViewDecimalColumn10.Calculation_Expression = null;
            xpertGridViewDecimalColumn10.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertGridViewDecimalColumn10.Calculative = false;
            xpertGridViewDecimalColumn10.Column_Name = null;
            xpertGridViewDecimalColumn10.Control_Name = "TotalQty";
            xpertGridViewDecimalColumn10.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModel;
            xpertGridViewDecimalColumn10.Custom_Data = false;
            xpertGridViewDecimalColumn10.Custom_Default = false;
            xpertGridViewDecimalColumn10.Display_Name = null;
            xpertGridViewDecimalColumn10.Field_Description = null;
            xpertGridViewDecimalColumn10.Field_Name = null;
            xpertGridViewDecimalColumn10.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertGridViewDecimalColumn10.FieldName = "TotalQty";
            xpertGridViewDecimalColumn10.Generated = false;
            xpertGridViewDecimalColumn10.HeaderText = "Total Quantity";
            xpertGridViewDecimalColumn10.MendatroryField = false;
            xpertGridViewDecimalColumn10.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            xpertGridViewDecimalColumn10.Name = "TotalQty";
            xpertGridViewDecimalColumn10.Validation_Criteria = null;
            xpertGridViewDecimalColumn10.Visibility_Criteria = null;
            xpertGridViewDecimalColumn10.XpertBindingSource = (XS.WinForms.Controls.FinderConfig)resources.GetObject("xpertGridViewDecimalColumn10.XpertBindingSource");
            xpertGridViewDecimalColumn10.XpertDisplayMember = null;
            xpertGridViewDecimalColumn10.XpertValueMember = null;
            xpertGridViewDecimalColumn10.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            gv1.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] { xpertGridViewDecimalColumn6, xpertGridViewFinderColumn2, xpertGridViewLabelColumn3, xpertGridViewLabelColumn4, xpertGridViewDecimalColumn7, xpertGridViewDecimalColumn8, xpertGridViewDecimalColumn9, xpertGridViewDecimalColumn10 });
            gv1.MasterTemplate.ShowHeaderCellButtons = true;
            gv1.MasterTemplate.ViewDefinition = tableViewDefinition2;
            gv1.MendatroryField = false;
            gv1.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            gv1.MultiSelection = false;
            gv1.Name = "gv1";
            gv1.Size = new System.Drawing.Size(961, 154);
            gv1.TabIndex = 0;
            gv1.Table_Name = "TSPL_PO_Item";
            gv1.Usage_Type = XpertStudio.Common.Enums.XSGridUsageType.None;
            gv1.Validation_Criteria = null;
            gv1.Visibility_Criteria = "";
            gv1.XpertDisplayMember = null;
            gv1.XpertValueMember = null;
            gv1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblAmount
            // 
            lblAmount.Calculation_Expression = null;
            lblAmount.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblAmount.Calculative = false;
            lblAmount.Column_Name = null;
            lblAmount.Control_Name = "lblAmount";
            lblAmount.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblAmount.Custom_Data = false;
            lblAmount.Custom_Default = false;
            lblAmount.Display_Name = null;
            lblAmount.Field_Description = null;
            lblAmount.Field_Name = null;
            lblAmount.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblAmount.FieldName = null;
            lblAmount.Generated = false;
            lblAmount.Location = new System.Drawing.Point(33, 104);
            lblAmount.MendatroryField = false;
            lblAmount.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblAmount.Name = "lblAmount";
            lblAmount.Size = new System.Drawing.Size(47, 18);
            lblAmount.SourceColumn = null;
            lblAmount.TabIndex = 10;
            lblAmount.Text = "Amount";
            lblAmount.Validation_Criteria = null;
            lblAmount.Visibility_Criteria = null;
            lblAmount.XpertDisplayMember = null;
            lblAmount.XpertValueMember = null;
            lblAmount.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblPODate
            // 
            lblPODate.Calculation_Expression = null;
            lblPODate.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblPODate.Calculative = false;
            lblPODate.Column_Name = null;
            lblPODate.Control_Name = "lblPODate";
            lblPODate.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblPODate.Custom_Data = false;
            lblPODate.Custom_Default = false;
            lblPODate.Display_Name = null;
            lblPODate.Field_Description = null;
            lblPODate.Field_Name = null;
            lblPODate.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblPODate.FieldName = null;
            lblPODate.Generated = false;
            lblPODate.Location = new System.Drawing.Point(402, 31);
            lblPODate.MendatroryField = false;
            lblPODate.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblPODate.Name = "lblPODate";
            lblPODate.Size = new System.Drawing.Size(30, 18);
            lblPODate.SourceColumn = null;
            lblPODate.TabIndex = 9;
            lblPODate.Text = "Date";
            lblPODate.Validation_Criteria = null;
            lblPODate.Visibility_Criteria = null;
            lblPODate.XpertDisplayMember = null;
            lblPODate.XpertValueMember = null;
            lblPODate.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // dtpPODate
            // 
            dtpPODate.Calculation_Expression = null;
            dtpPODate.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            dtpPODate.CalculationExpression = null;
            dtpPODate.Calculative = false;
            dtpPODate.Column_Name = "PODate";
            dtpPODate.Control_Name = "dtpPODate";
            dtpPODate.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            dtpPODate.Custom_Data = false;
            dtpPODate.Custom_Default = false;
            dtpPODate.CustomFormat = "dd/MM/yyyy";
            dtpPODate.Display_Name = "Date";
            dtpPODate.Field_Description = null;
            dtpPODate.Field_Name = "PODate";
            dtpPODate.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            dtpPODate.FieldCode = null;
            dtpPODate.FieldDesc = null;
            dtpPODate.FieldMaxLength = 0;
            dtpPODate.FieldName = "PODate";
            dtpPODate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            dtpPODate.Generated = false;
            dtpPODate.isCalculatedField = false;
            dtpPODate.IsSourceFromTable = false;
            dtpPODate.IsSourceFromValueList = false;
            dtpPODate.IsUnique = false;
            dtpPODate.Key = false;
            dtpPODate.Location = new System.Drawing.Point(438, 30);
            dtpPODate.Max_Length = 0;
            dtpPODate.MendatroryField = false;
            dtpPODate.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            dtpPODate.Min_Length = 0;
            dtpPODate.MyLinkLable1 = lblPODate;
            dtpPODate.MyLinkLable2 = null;
            dtpPODate.Name = "dtpPODate";
            dtpPODate.ReferenceFieldDesc = null;
            dtpPODate.ReferenceFieldName = "PODate";
            dtpPODate.ReferenceTableName = null;
            dtpPODate.Size = new System.Drawing.Size(140, 20);
            dtpPODate.TabIndex = 8;
            dtpPODate.TabStop = false;
            dtpPODate.Text = "21-05-2024";
            dtpPODate.Validation_Criteria = null;
            dtpPODate.Value = new System.DateTime(2024, 5, 21, 21, 46, 27, 98);
            dtpPODate.Visibility_Criteria = null;
            dtpPODate.XpertDisplayMember = null;
            dtpPODate.XpertValueMember = null;
            dtpPODate.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtComments
            // 
            txtComments.Calculation_Expression = null;
            txtComments.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtComments.CalculationExpression = null;
            txtComments.Calculative = false;
            txtComments.Column_Name = "POComment";
            txtComments.Control_Name = "txtComments";
            txtComments.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtComments.Custom_Data = false;
            txtComments.Custom_Default = false;
            txtComments.Display_Name = "Comments";
            txtComments.Field_Description = null;
            txtComments.Field_Name = "Description";
            txtComments.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.Description;
            txtComments.FieldCode = null;
            txtComments.FieldDesc = null;
            txtComments.FieldMaxLength = 50;
            txtComments.FieldName = "Description";
            txtComments.Generated = false;
            txtComments.isCalculatedField = false;
            txtComments.IsSourceFromTable = false;
            txtComments.IsSourceFromValueList = false;
            txtComments.IsUnique = false;
            txtComments.Key = false;
            txtComments.Location = new System.Drawing.Point(125, 57);
            txtComments.Max_Length = 50;
            txtComments.MendatroryField = false;
            txtComments.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtComments.Min_Length = 0;
            txtComments.MyLinkLable1 = lblComments;
            txtComments.MyLinkLable2 = null;
            txtComments.Name = "txtComments";
            txtComments.ReferenceFieldDesc = null;
            txtComments.ReferenceFieldName = "Description";
            txtComments.ReferenceTableName = null;
            txtComments.Size = new System.Drawing.Size(378, 20);
            txtComments.TabIndex = 7;
            txtComments.Validation_Criteria = null;
            txtComments.Visibility_Criteria = null;
            txtComments.XpertDisplayMember = null;
            txtComments.XpertValueMember = null;
            txtComments.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblComments
            // 
            lblComments.Calculation_Expression = null;
            lblComments.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblComments.Calculative = false;
            lblComments.Column_Name = null;
            lblComments.Control_Name = "lblDescription";
            lblComments.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblComments.Custom_Data = false;
            lblComments.Custom_Default = false;
            lblComments.Display_Name = null;
            lblComments.Field_Description = null;
            lblComments.Field_Name = null;
            lblComments.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblComments.FieldName = null;
            lblComments.Generated = false;
            lblComments.Location = new System.Drawing.Point(33, 59);
            lblComments.MendatroryField = false;
            lblComments.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblComments.Name = "lblComments";
            lblComments.Size = new System.Drawing.Size(60, 18);
            lblComments.SourceColumn = null;
            lblComments.TabIndex = 6;
            lblComments.Text = "Comments";
            lblComments.Validation_Criteria = null;
            lblComments.Visibility_Criteria = null;
            lblComments.XpertDisplayMember = null;
            lblComments.XpertValueMember = null;
            lblComments.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // lblPONo
            // 
            lblPONo.Calculation_Expression = null;
            lblPONo.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            lblPONo.Calculative = false;
            lblPONo.Column_Name = null;
            lblPONo.Control_Name = "lblDocNo";
            lblPONo.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            lblPONo.Custom_Data = false;
            lblPONo.Custom_Default = false;
            lblPONo.Display_Name = null;
            lblPONo.Field_Description = null;
            lblPONo.Field_Name = null;
            lblPONo.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            lblPONo.FieldName = null;
            lblPONo.Generated = false;
            lblPONo.Location = new System.Drawing.Point(33, 31);
            lblPONo.MendatroryField = false;
            lblPONo.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.None;
            lblPONo.Name = "lblPONo";
            lblPONo.Size = new System.Drawing.Size(39, 18);
            lblPONo.SourceColumn = null;
            lblPONo.TabIndex = 5;
            lblPONo.Text = "PO No";
            lblPONo.Validation_Criteria = null;
            lblPONo.Visibility_Criteria = null;
            lblPONo.XpertDisplayMember = null;
            lblPONo.XpertValueMember = null;
            lblPONo.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtPOCode
            // 
            txtPOCode.Calculation_Expression = null;
            txtPOCode.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtPOCode.Calculative = false;
            txtPOCode.Column_Name = "POCode";
            txtPOCode.Control_Name = "txtPOCode";
            txtPOCode.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtPOCode.Custom_Data = false;
            txtPOCode.Custom_Default = false;
            txtPOCode.DataSource = null;
            txtPOCode.Display_Name = "PO No";
            txtPOCode.DisplayMember = null;
            txtPOCode.Field_Description = null;
            txtPOCode.Field_Name = "POCode";
            txtPOCode.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.ID;
            txtPOCode.FieldName = "POCode";
            txtPOCode.Generated = false;
            txtPOCode.Key = false;
            txtPOCode.Location = new System.Drawing.Point(125, 27);
            txtPOCode.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            txtPOCode.Max_Length = 10;
            txtPOCode.Max_Size = 0;
            txtPOCode.MendatroryField = false;
            txtPOCode.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtPOCode.Min_Length = 0;
            txtPOCode.Min_Size = 0;
            txtPOCode.MyCharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            txtPOCode.MyFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            txtPOCode.MyLinkLable1 = lblPONo;
            txtPOCode.MyLinkLable2 = null;
            txtPOCode.MyMaxLength = 32767;
            txtPOCode.MyNewEnable = true;
            txtPOCode.MyNewPerformClick = false;
            txtPOCode.MyNewVisible = true;
            txtPOCode.MyReadOnly = false;
            txtPOCode.Name = "txtPOCode";
            txtPOCode.Required = false;
            txtPOCode.Size = new System.Drawing.Size(258, 24);
            txtPOCode.TabIndex = 4;
            txtPOCode.Validation_Criteria = null;
            txtPOCode.Value = "";
            txtPOCode.ValueMember = null;
            txtPOCode.Visibility_Criteria = null;
            txtPOCode.XpertDisplayMember = null;
            txtPOCode.XpertValueMember = null;
            txtPOCode.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertPageView1
            // 
            xpertPageView1.BorderColor = System.Drawing.Color.Black;
            xpertPageView1.Control_Name = "xpertPageView1";
            xpertPageView1.Controls.Add(Page1);
            xpertPageView1.Controls.Add(Page2);
            xpertPageView1.Dock = System.Windows.Forms.DockStyle.Fill;
            xpertPageView1.Location = new System.Drawing.Point(0, 0);
            xpertPageView1.Name = "xpertPageView1";
            xpertPageView1.SelectedPage = Page1;
            xpertPageView1.Size = new System.Drawing.Size(986, 392);
            xpertPageView1.TabIndex = 0;
            xpertPageView1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // Page1
            // 
            Page1.Controls.Add(xpertSplitContainer1);
            Page1.ItemSize = new System.Drawing.SizeF(55F, 28F);
            Page1.Location = new System.Drawing.Point(10, 37);
            Page1.Name = "Page1";
            Page1.Size = new System.Drawing.Size(965, 344);
            Page1.Text = "General";
            // 
            // Page2
            // 
            Page2.Controls.Add(xpertGroupBox1);
            Page2.ItemSize = new System.Drawing.SizeF(50F, 28F);
            Page2.Location = new System.Drawing.Point(10, 37);
            Page2.Name = "Page2";
            Page2.Size = new System.Drawing.Size(965, 344);
            Page2.Text = "Others";
            // 
            // xpertGroupBox1
            // 
            xpertGroupBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            xpertGroupBox1.BorderColor = System.Drawing.Color.Empty;
            xpertGroupBox1.Control_Name = "xpertGroupBox1";
            xpertGroupBox1.Controls.Add(xpertGroupBox3);
            xpertGroupBox1.Controls.Add(xpertLabel1);
            xpertGroupBox1.Controls.Add(txtItems);
            xpertGroupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            xpertGroupBox1.GroupBoxStyle = Telerik.WinControls.UI.RadGroupBoxStyle.Office;
            xpertGroupBox1.HeaderText = "Testing";
            xpertGroupBox1.Location = new System.Drawing.Point(0, 0);
            xpertGroupBox1.Name = "xpertGroupBox1";
            xpertGroupBox1.Size = new System.Drawing.Size(965, 344);
            xpertGroupBox1.TabIndex = 0;
            xpertGroupBox1.Text = "Testing";
            xpertGroupBox1.Visibility_Criteria = null;
            xpertGroupBox1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertGroupBox3
            // 
            xpertGroupBox3.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            xpertGroupBox3.BorderColor = System.Drawing.Color.Empty;
            xpertGroupBox3.Control_Name = null;
            xpertGroupBox3.Controls.Add(xpertRadioButton2);
            xpertGroupBox3.Controls.Add(xpertRadioButton1);
            xpertGroupBox3.HeaderText = "Options";
            xpertGroupBox3.Location = new System.Drawing.Point(194, 119);
            xpertGroupBox3.Name = "xpertGroupBox3";
            xpertGroupBox3.Size = new System.Drawing.Size(387, 100);
            xpertGroupBox3.TabIndex = 2;
            xpertGroupBox3.Text = "Options";
            xpertGroupBox3.Visibility_Criteria = null;
            xpertGroupBox3.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertRadioButton2
            // 
            xpertRadioButton2.BackColor = System.Drawing.Color.White;
            xpertRadioButton2.Calculation_Expression = null;
            xpertRadioButton2.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertRadioButton2.CalculationExpression = null;
            xpertRadioButton2.Calculative = false;
            xpertRadioButton2.Column_Name = null;
            xpertRadioButton2.Control_Name = null;
            xpertRadioButton2.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertRadioButton2.Custom_Data = false;
            xpertRadioButton2.Custom_Default = false;
            xpertRadioButton2.Display_Name = null;
            xpertRadioButton2.Field_Description = null;
            xpertRadioButton2.Field_Name = "PO_Options";
            xpertRadioButton2.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertRadioButton2.FieldCode = null;
            xpertRadioButton2.FieldDesc = null;
            xpertRadioButton2.FieldMaxLength = 0;
            xpertRadioButton2.FieldName = "PO_Options";
            xpertRadioButton2.Generated = false;
            xpertRadioButton2.isCalculatedField = false;
            xpertRadioButton2.IsSourceFromTable = false;
            xpertRadioButton2.IsSourceFromValueList = false;
            xpertRadioButton2.IsUnique = false;
            xpertRadioButton2.Key = false;
            xpertRadioButton2.Location = new System.Drawing.Point(191, 43);
            xpertRadioButton2.Max_Length = 0;
            xpertRadioButton2.MendatroryField = false;
            xpertRadioButton2.Metadata_Type = null;
            xpertRadioButton2.Min_Length = 0;
            xpertRadioButton2.MyLinkLable1 = null;
            xpertRadioButton2.MyLinkLable2 = null;
            xpertRadioButton2.Name = "xpertRadioButton2";
            xpertRadioButton2.ReferenceFieldDesc = null;
            xpertRadioButton2.ReferenceFieldName = "PO_Options";
            xpertRadioButton2.ReferenceTableName = null;
            xpertRadioButton2.Size = new System.Drawing.Size(61, 18);
            xpertRadioButton2.TabIndex = 3;
            xpertRadioButton2.Text = "Option2";
            xpertRadioButton2.Validation_Criteria = null;
            xpertRadioButton2.Visibility_Criteria = null;
            xpertRadioButton2.XpertDisplayMember = null;
            xpertRadioButton2.XpertValueMember = null;
            xpertRadioButton2.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertRadioButton1
            // 
            xpertRadioButton1.BackColor = System.Drawing.Color.White;
            xpertRadioButton1.Calculation_Expression = null;
            xpertRadioButton1.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertRadioButton1.CalculationExpression = null;
            xpertRadioButton1.Calculative = false;
            xpertRadioButton1.Column_Name = null;
            xpertRadioButton1.Control_Name = null;
            xpertRadioButton1.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertRadioButton1.Custom_Data = false;
            xpertRadioButton1.Custom_Default = false;
            xpertRadioButton1.Display_Name = null;
            xpertRadioButton1.Field_Description = null;
            xpertRadioButton1.Field_Name = "PO_Options";
            xpertRadioButton1.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertRadioButton1.FieldCode = null;
            xpertRadioButton1.FieldDesc = null;
            xpertRadioButton1.FieldMaxLength = 0;
            xpertRadioButton1.FieldName = "PO_Options";
            xpertRadioButton1.Generated = false;
            xpertRadioButton1.isCalculatedField = false;
            xpertRadioButton1.IsSourceFromTable = false;
            xpertRadioButton1.IsSourceFromValueList = false;
            xpertRadioButton1.IsUnique = false;
            xpertRadioButton1.Key = false;
            xpertRadioButton1.Location = new System.Drawing.Point(32, 43);
            xpertRadioButton1.Max_Length = 0;
            xpertRadioButton1.MendatroryField = false;
            xpertRadioButton1.Metadata_Type = null;
            xpertRadioButton1.Min_Length = 0;
            xpertRadioButton1.MyLinkLable1 = null;
            xpertRadioButton1.MyLinkLable2 = null;
            xpertRadioButton1.Name = "xpertRadioButton1";
            xpertRadioButton1.ReferenceFieldDesc = null;
            xpertRadioButton1.ReferenceFieldName = "PO_Options";
            xpertRadioButton1.ReferenceTableName = null;
            xpertRadioButton1.Size = new System.Drawing.Size(61, 18);
            xpertRadioButton1.TabIndex = 2;
            xpertRadioButton1.Text = "Option1";
            xpertRadioButton1.Validation_Criteria = null;
            xpertRadioButton1.Visibility_Criteria = null;
            xpertRadioButton1.XpertDisplayMember = null;
            xpertRadioButton1.XpertValueMember = null;
            xpertRadioButton1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // xpertLabel1
            // 
            xpertLabel1.Calculation_Expression = null;
            xpertLabel1.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            xpertLabel1.Calculative = false;
            xpertLabel1.Column_Name = null;
            xpertLabel1.Control_Name = null;
            xpertLabel1.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            xpertLabel1.Custom_Data = false;
            xpertLabel1.Custom_Default = false;
            xpertLabel1.Display_Name = null;
            xpertLabel1.Field_Description = null;
            xpertLabel1.Field_Name = null;
            xpertLabel1.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.None;
            xpertLabel1.FieldName = null;
            xpertLabel1.Generated = false;
            xpertLabel1.Location = new System.Drawing.Point(88, 76);
            xpertLabel1.MendatroryField = false;
            xpertLabel1.Metadata_Type = null;
            xpertLabel1.Name = "xpertLabel1";
            xpertLabel1.Size = new System.Drawing.Size(66, 18);
            xpertLabel1.SourceColumn = null;
            xpertLabel1.TabIndex = 1;
            xpertLabel1.Text = "Select Items";
            xpertLabel1.Validation_Criteria = null;
            xpertLabel1.Visibility_Criteria = null;
            xpertLabel1.XpertDisplayMember = null;
            xpertLabel1.XpertValueMember = null;
            xpertLabel1.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // txtItems
            // 
            txtItems.arrDispalyMember = null;
            txtItems.arrValueMember = null;
            txtItems.Calculation_Expression = null;
            txtItems.Calculation_Type = XS.WinForms.Controls.CalculationTypes.None;
            txtItems.Calculative = false;
            txtItems.Collection_Name = null;
            txtItems.Column_Name = "POItemList";
            txtItems.Control_Name = "XpertMultiSelctFinder";
            txtItems.Create_Option = XpertStudio.Common.Enums.XpertFieldCreateOptions.UIAndModelAndTable;
            txtItems.Custom_Data = false;
            txtItems.Custom_Datasource_Logic = false;
            txtItems.Custom_Default = false;
            txtItems.DataSource = null;
            txtItems.Datasource_Assembly = "BlazorPWA.Client";
            txtItems.Datasource_Namespace = "BlazorPWA.Client.Pages.MachineTest.Setup";
            txtItems.Datasource_Program = "ItemMaster";
            txtItems.Datasource_Type = XpertStudio.Common.Enums.XpertFinderConfigType.Pages;
            txtItems.Display_Name = "Item List";
            txtItems.DisplayMember = null;
            txtItems.Enum_Name = null;
            txtItems.Field_Description = null;
            txtItems.Field_Name = "POItemList";
            txtItems.Field_Type = XpertStudio.Common.Enums.XpertFieldTypes.MultiSelectFinder;
            txtItems.Generated = false;
            txtItems.Key = false;
            txtItems.Key_Column_Name = "ICode";
            txtItems.Key_Property = null;
            txtItems.Key_Value = null;
            txtItems.Location = new System.Drawing.Point(194, 71);
            txtItems.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            txtItems.Max_Size = 0;
            txtItems.MendatroryField = false;
            txtItems.Metadata_Type = XpertStudio.Common.Enums.XpertMetadataTypes.Auto;
            txtItems.Min_Size = 0;
            txtItems.MinimumSize = new System.Drawing.Size(117, 23);
            txtItems.Model_Name = null;
            txtItems.MyFont = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            txtItems.MyLinkLable1 = null;
            txtItems.MyLinkLable2 = null;
            txtItems.MyNullText = "All";
            txtItems.MyReadOnly = false;
            txtItems.MyToolTipText = null;
            txtItems.Name = "txtItems";
            txtItems.Name_Column_Name = "IName";
            txtItems.Name_Property = null;
            txtItems.Name_Value = null;
            txtItems.Page_Key_Property = "ID";
            txtItems.Page_Name_Property = "Description";
            txtItems.Query_Class_Name = null;
            txtItems.Required = false;
            txtItems.Section_Class = "clsFinderItems";
            txtItems.Section_Table = "FinderItems";
            txtItems.ShowDataSource = false;
            txtItems.Size = new System.Drawing.Size(233, 25);
            txtItems.SQLMethodName = null;
            txtItems.TabIndex = 0;
            txtItems.Table_Name = "TSPL_ITEM_MASTER";
            txtItems.Tag_Column_Name = null;
            txtItems.Tag_Property = null;
            txtItems.Validation_Criteria = null;
            txtItems.ValueMember = null;
            txtItems.Visibility_Criteria = null;
            txtItems.Web_Page_Name = "ItemMaster";
            txtItems.Web_Page_Url = "/MachineTest/Setup/ItemMaster";
            txtItems.XpertDisplayMember = null;
            txtItems.XpertValueMember = null;
            txtItems.XS_Skip = XpertStudio.Common.Enums.XS_SkipTypes.None;
            // 
            // frmPurchaseOrder
            // 
            ApproveCommandVisibility = false;
            AuthPolicy = XpertStudio.Common.Authorization.XsPolicies.AnonymousUser;
            AutoScaleBaseSize = new System.Drawing.Size(7, 15);
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Class_File_Name = "frmPurchaseOrder.cs";
            Class_Name = "clsPurchaseOrder";
            ClientSize = new System.Drawing.Size(986, 430);
            Controls.Add(xpertPageView1);
            CreateCommandServiceClass = "clsPurchaseOrderCreateCommand";
            CurrentEditorType = "frmRuleEditor";
            DataProxyLayerClass = "IclsPurchaseOrderDataProxy";
            DeleteCommandServiceClass = "clsPurchaseOrderDeleteCommand";
            Doc_Prefix = "PO";
            DomainLayerClass = "clsPurchaseOrder";
            DomainRulesClass = "clsPurchaseOrderRules";
            EnableAddButton = true;
            ExternalAssemblies.Assemblies = (System.Collections.Generic.List<string>)resources.GetObject("resource.Assemblies");
            File_Name = "frmPurchaseOrder.cs";
            File_Path = "D:\\Official\\XpertGitHubProjects\\MachineTest\\WinFormUI3Tier\\Designers\\frmPurchaseOrder.cs";
            Form_Name = "frmPurchaseOrder";
            Form_Type = XpertStudio.Common.Enums.XpertFormTypes.Transaction;
            Functional_Name = "PurchaseOrder";
            IServiceLayerClass = "IclsPurchaseOrderService";
            MaxFieldsListPage = 5;
            ModuleName = "MachineTest";
            Name = "frmPurchaseOrder";
            Program_Code = "PurchaseOrder";
            Program_Name = "Purchase Order";
            QueryClass = "clsPurchaseOrderQueries";
            RepositoryLayerClass = "clsPurchaseOrderRepository";
            ServiceLayerClass = "clsPurchaseOrderService";
            SubModuleName = "Transaction";
            Table_Name = "TSPL_PO";
            Text = "frmPurchaseOrder";
            UpdateCommandServiceClass = "clsPurchaseOrderUpdateCommand";
            WinFormUILayerClass = "clsPurchaseOrderWinFormUI";
            Load += XSTransactionSimple_Load;
            Controls.SetChildIndex(xpertPageView1, 0);
            ((System.ComponentModel.ISupportInitialize)bindingSource1).EndInit();
            xpertSplitContainer1.Panel1.ResumeLayout(false);
            xpertSplitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)xpertSplitContainer1).EndInit();
            xpertSplitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gbxHeader).EndInit();
            gbxHeader.ResumeLayout(false);
            gbxHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox2).EndInit();
            xpertGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pcbPhoto).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblVendor).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblDocumentAmount).EndInit();
            ((System.ComponentModel.ISupportInitialize)txtDocAmt).EndInit();
            ((System.ComponentModel.ISupportInitialize)dtpModifyDate).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblModifyDate).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblCreateDateTime).EndInit();
            ((System.ComponentModel.ISupportInitialize)dtpCreateDateTime).EndInit();
            ((System.ComponentModel.ISupportInitialize)txtRemarks).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblRemarks).EndInit();
            ((System.ComponentModel.ISupportInitialize)txtPOAmt).EndInit();
            ((System.ComponentModel.ISupportInitialize)gbxDetails).EndInit();
            gbxDetails.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gv1.MasterTemplate).EndInit();
            ((System.ComponentModel.ISupportInitialize)gv1).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblAmount).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblPODate).EndInit();
            ((System.ComponentModel.ISupportInitialize)dtpPODate).EndInit();
            ((System.ComponentModel.ISupportInitialize)txtComments).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblComments).EndInit();
            ((System.ComponentModel.ISupportInitialize)lblPONo).EndInit();
            ((System.ComponentModel.ISupportInitialize)xpertPageView1).EndInit();
            xpertPageView1.ResumeLayout(false);
            Page1.ResumeLayout(false);
            Page2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox1).EndInit();
            xpertGroupBox1.ResumeLayout(false);
            xpertGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)xpertGroupBox3).EndInit();
            xpertGroupBox3.ResumeLayout(false);
            xpertGroupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)xpertRadioButton2).EndInit();
            ((System.ComponentModel.ISupportInitialize)xpertRadioButton1).EndInit();
            ((System.ComponentModel.ISupportInitialize)xpertLabel1).EndInit();
            ((System.ComponentModel.ISupportInitialize)this).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private XS.WinForms.Controls.XpertSplitContainer xpertSplitContainer1;
        private XS.WinForms.Controls.XpertPageView xpertPageView1;
        private Telerik.WinControls.UI.RadPageViewPage Page1;
        private Telerik.WinControls.UI.RadPageViewPage Page2;
        private XS.WinForms.Controls.XpertGroupBox gbxHeader;
        private XS.WinForms.Controls.XpertGroupBox gbxDetails;
        private XS.WinForms.Controls.XpertGroupBox xpertGroupBox1;
        private XS.WinForms.Controls.XpertTextBox txtComments;
        private XS.WinForms.Controls.XpertLabel lblComments;
        private XS.WinForms.Controls.XpertLabel lblPONo;
        private XS.WinForms.Controls.XpertNavigator txtPOCode;
        private XS.WinForms.Controls.XpertDataGridView gv1;
        private XS.WinForms.Controls.XpertLabel lblPODate;
        private XS.WinForms.Controls.XpertDateTime dtpPODate;
        private XS.WinForms.Controls.XpertLabel lblAmount;
        private XS.WinForms.Controls.XpertNumberBox txtPOAmt;
        private XS.WinForms.Controls.XpertTextBox txtRemarks;
        private XS.WinForms.Controls.XpertLabel lblRemarks;
        private XS.WinForms.Controls.XpertLabel lblCreateDateTime;
        private XS.WinForms.Controls.XpertDateTime dtpCreateDateTime;
        private XS.WinForms.Controls.XpertDateTime dtpModifyDate;
        private XS.WinForms.Controls.XpertLabel lblModifyDate;
        private XS.WinForms.Controls.XpertLabel lblVendor;
        private XS.WinForms.Controls.XpertFinder txtVendor;
        private XS.WinForms.Controls.XpertNumberBox txtDocAmt;
        private XS.WinForms.Controls.XpertLabel lblDocumentAmount;
        private XS.WinForms.Controls.XpertPictureBox pcbPhoto;
        private XS.WinForms.Controls.XpertGroupBox xpertGroupBox2;
        private XS.WinForms.Controls.XpertMultiSelctFinder txtItems;
        private XS.WinForms.Controls.XpertLabel xpertLabel1;
        private XS.WinForms.Controls.XpertGroupBox xpertGroupBox3;
        private XS.WinForms.Controls.XpertRadioButton xpertRadioButton2;
        private XS.WinForms.Controls.XpertRadioButton xpertRadioButton1;
    }
}